version: '3'

services:
  mysql-server:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=${ADMIN_JWT_SECRET}
      - MYSQL_DATABASE=strapi
    volumes:
      - ./.data:/var/lib/mysql
    ports:
      - 3306:3306
    restart: always

  strapi-server:
    depends_on:
      - mysql-server
    image: ohp/strapi-server
    environment:
      - DATABASE_CLIENT=mysql2
      - DATABASE_HOST=mysql-server
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=${ADMIN_JWT_SECRET}
      - NODE_ENV=production
      - PORT=1337
    ports:
      - 1337:1337
    healthcheck:
      test: ['CMD-SHELL', 'curl -f http://localhost:1337/ || exit 1']
      interval: 3s
      retries: 5
      start_period: 30s
    labels:
      - autoheal=true
    restart: always

  autoheal:
    image: willfarrell/autoheal:1.2.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
